### ISSUE TITLE
App deployment on trusted connector

### ISSUE THREAD

**Issue by spetrac** [industrial-data-space/trusted-connector#160]
I tried to reach you personally, but I could not get an answer, so I decided to state my questions here:

I got the trusted connector to run in a container environment and I would like to find out how the deployment of apps and the operation of apps works with the container. I have the following questions:

- **How do I install apps?** I build and launched the trusted-connector, but in the app selection all suggestions seem to be dummies, because nothing happens if I click "install".
- **How do I program new apps?** From my knowledge apps must be deployed as some kind of container images, therefore I am interested in the API from the app container to the connector to publish services and to use the connector infrastructure. Is there any standard for this app containers to be possibly compatible with other connector implementations?
- **How do I publish apps?** It seemed to me that the trusted connector could not install arbitrary images from docker, even if the selection of database apps suggested this. Examples like "IDS REST Server Example" or "IDS Data Provider Example" must come from somewhere or are they hard-coded?
- **What does the future hold for the trusted connector?** Will the software be developed further and made usable for production or are there any other usable alternatives?

**Comment by milux** [comment]
Sorry, my bad, your mail scrolled out of my focus before I had time to handle it. :see_no_evil: 

- **How do I install apps?** - Apps in the TC are just Docker images. Installation should fetch a docker image and create a new container of it. There is currently not implemented anything beyond that, because there was never a viable spec for any interfaces at the time we actively developed on this.
You should find a config option inside the TC settings where you can set the URL of a Portainer-format JSON. This will be the source for the apps you can install, the "repository", if you will.
- **How do I program new apps?** - You create a Docker image.
- **How do I publish apps?** - You put a Docker image into the "repository", i.e. JSON, used by the TC.
- **Future** - The Trusted Connector currently receives only minor updates and fixes, and sometimes we used it as a testing board for new features that are or have been actively developed. Recently EST (re)enrollment, for instance.
However, improved usability, let alone production-readiness, is not planned.

**Comment by milux** [comment]
Just wanted to add that developing anything to the point of production-readiness **internally** is extremely untypical for Fraunhofer in general.
We mostly develop prototypes, production-readiness does only get relevant in (paid) coops with the industry.

And regarding usable alternatives: A well-known framework still being worked on is the EDC (Eclipse Dataspace Connector). However, it's also not a product at all in that sense, and AFAIK there is neither a user interface nor a concept for integrated apps there at all.

**Comment by spetrac** [comment]
Yes, I am currently in the process to develop a deployment strategy of the EDC for the DataBri-X project, but the connector implementation deviated much from the initial idea of a connector from the IDS and I was searching for other options in the ecosystem.

**Comment by gbrost** [comment]
For a project such as data-brix, where the TRL requirements are not that high (I guess?) it should be possible to facility the trusted connector. We used it in a number of scenarios to perform data exchange. In Safe4Soc we will also have the need to use a gateway in this manner. The technical baseline is pretty stable. The GUI has not been kept very up to date so we have some empty interfaces und unimplemented features (such as automated container deployment). We would use one of the examples and modify them. This works well if you adjust the docker-compose files and data routes.

**Comment by spetrac** [comment]
The project is currently stuck on DSC and decided to change the connector technology to EDC, because it is versatile, further developed and already adopted by other projects. I looked into the trusted-connector also for possible future usage, but I don't see how I would use it as a gateway at the moment. Adjusting the deployment alone does not change the connector and modifying source code is just as tedious as with every other connector and comes down to the quality of the documentation and the application itself, which I cannot estimate at the moment.
A UI is absolutely not necessary for usage as a gateway and the reasons I would decide for the trusted-connector would mostly be the ability to install apps. This would enable non-IDS services to  benefit from IDS security, trust and infrastructure, although this would imply a proper integration of apps into the container infrastructure and at best a support for usage policies on top. 
The DataBri-X project has already decided for the EDC, so there is no room for argumentation anyway. The only question for me at the moment is the best deployment of the EDC in the IDS ecosystem and the most prominent candidate currently is the edc-ce from sovity.
Production readyness is just a very important attribute and if IDS connector technology wants to have a chance in the market, reliable connector software has to be developed as well as reliable infrastructure components. Without it, the project will just collapse on itself as their are already so many deviations that you could hardly speak of a standardized approach.

**Comment by gbrost** [comment]
Btw you would not have to change source code besides the Camel routes to customise the connector. Anyhow, we will have a chance to discuss this in SAFE4SOC. 
For the rest I agree, but let us continue on another channel.

**Comment by milux** [comment]
> [...] and modifying source code is just as tedious as with every other connector [...]

Well, no on that aspect. TC code is cleaner and easier to read in many places due to the usage of Kotlin. EDC is stuck with Java and decision-makers are unwilling to move on to a more modern, compatible language.
That's indeed a shortcoming you have to deal with in case you want to do any kind of modification to core components etc.
If you are just interfacing them, no problem, except for the fact that readability is also impaired to some degree.
