### ISSUE TITLE
Trusted Connector Attestation

### ISSUE THREAD

**Issue by musi00** [industrial-data-space/trusted-connector#34]
Hello,

This is not an issue but more of a question.  Please let me know if there is a better channel to post my question.  

I have read the trusted connector and trust|me documentation and trying to understand the limitation of Remote Attestation within the contest of a trusted connector implemented using trust|me.

**Base System Attestation**
As I understand it, remote attestation allows a trusted connector to verify the software stack of another trusted connector.
1) How far up the software stack does this attestation go.  Specifically, if we were using trust|me does this verification simply ensure that we are running the base system of trust|me?

2) Part of the secure boot feature of trust|me is a step that ensures the boot loader software was signed by a Software CA.  What if the trusted connector I'm trying to verify has an invalid certificate in their UEFI signature DB.  Can remote attestation help with this in any way?

**Custom Container (Guess OS) Signature Validation**

3) By verifying that a proper base system is running you can be confident that only signed software will be deployed inside the custom containers.  However this is only guaranteed if the certificate store of the base system contains only valid software signing certificates.  How does one connector ensure that the certificate store of the other connector is valid? Does remote attestation check the certificate store as well?

4) The base system verifies the signature of GuesOS's in the custom containers.  However does it also verify the applications running on the GuestOS.  Is verifying the GuesOS only good enough?

Thank you for your time

**Comment by gbrost** [comment]
Thank you for your question. Especially thank you for preparing your question and reading the available documentation. I will try to answer as best as I can:

1. At the moment, this is pretty much the case. However, we plan to extend the concept to measure all of the components. The idea is to have a compositional attestation where all artefacts can be attested. 
2. I will forward that question. I believe this might be an issue since if the root of trust is invalid, the PCR values that are written are probably invalid too. 
3. This needs to part of the attestation as well, correct. 
4. These are not really guest OSs as in VMs. And the idea is to have the full container image attested. But you are right: If you have dynamic module loading capabilities, you can create a problem there.

**Comment by musi00** [comment]
Thank you for your previous response, it clarified a few things.  As I am digging deeper into the trusted connector, I have a few follow up questions:

1) The trusted connector Admin interface provides APIs for installing and deleting certificates.  I wonder if this API can be used malicously by a data consumer.  It would go something like this:
  i) Provider verifies that consumer installed certificates are valid and therefore consumer bust only be able to install valid software.
  ii) Provider sends data to consumer
  iii) After the data is sent the consumer adds new certificates to be able to install untrusted software to process the data.  He should be able to do this since the remote attestation step has already completed.
can you please clarify whether this scenario is possible and if not why? if so, what are some workarounds?

**Comment by gbrost** [comment]
Hi, 

Please keep in mind we currently have a demo configuration where we try to make things easy. The interface for certificate configuration would not work if you were using a TPM since the certificates are generated for public keys where the matching private key is stored in a hardware trust anchor. The certificates used for software verification as a root of trust would be provisioned into UEFI. Both would need to be reset which requires a reboot. And this is why we have the certification criteria catalog and why it is so extensive. You need to take care of all the layers. You are right trustme uses this provisioning mode and makes sure it cannot be reenabled without losing all data. 
And these are the features you lose when using docker. We use a tpmsim for Demo purposes. And we did rewire it to a real TPM for some deployment scenarios (for showing that it works). But you need to take the whole system into account to make this useful (e.g, disabling the means to rewire the TPM).

**Comment by musi00** [comment]
Thanks for the clarification
