### ISSUE TITLE
Data Provenance and Clearing House

### ISSUE THREAD

**Issue by musi00** [industrial-data-space/trusted-connector#37]
Hello,

The documentation of the trusted connector only talks about usage control.  However, it does not address data flow tracking and logging at the clearing house.  Is this something already implemented? if not, what would be the starting point if someone wants to implement a data flow tracking module.

**Comment by gbrost** [comment]
Hi, 
we have "implicit" support for the Clearing House, since you can pretty easily embed that into a Camel route. Audit logging is somehow limited, however. A good starting point would be the PolicyEnforcementPoint, since this is triggered on every hop. 
So you could embed your logging capabilities there.
