### ISSUE TITLE
OSGiless: The future of dynamic TLS? 

### ISSUE THREAD

**Issue by oxisto** [industrial-data-space/trusted-connector#45]
Either remove it or extend to create dynamic TLS of the routes.

**Comment by milux** [comment]
Porting the SSL engine reload to the web UI of the Spring-based connector turns out to be more difficult then expected.
It requires switching from tomcat to jersey, and my initial approach was not working right away.
However, the components are now available to be used, when necessary.
Removed the milestone, because this is a long-running task with medium or low priority.
